language: node_js
node_js:
  - "8.9.3"
cache:
  directories:
    - "node_modules"
after_install:
  - npm i nyc codeclimate-test-reporter coveralls

before_script:
  - npm start &
  - sleep 10s

script:
  - ./node_modules/.bin/nyc npm test

after_script:
  - ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
  - ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov/lcov.info
