language: node_js
node_js:
  - "8.9.3"
cache:
  directories:
    - "node_modules"

before_install:
  - npm install -g greenkeeper-lockfile@1

before_script:
  - npm i nyc coveralls
  - greenkeeper-lockfile-update

script:
  - ./node_modules/.bin/nyc --check-coverage --lines 90 npm test --serial

after_script:
  - ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
  - greenkeeper-lockfile-upload
