language: node_js
node_js:
  - "8.9.3"
cache:
  directories:
    - "node_modules"

before_script:
  - npm i nyc codeclimate-test-reporter coveralls
  - npm start &
  - sleep 10s

script:
  - ./node_modules/.bin/nyc --reporter=text-lcov npm test

after_script:
  -  cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
  - ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
