# Test against the latest version of this Node.js version
environment:
  nodejs_version: "8.9.3"
  NODE_ENV: test
  PORT: 8383

# Save CI recourses
skip_branch_with_pr: true
clone_depth: 1
cache: 
  - node_modules

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version

  # start server
  - cmd.exe /c chcp 65001 > nul & cmd.exe /c  echo npm^ start > server.bat
  - ps: Start-Process -FilePath "server.bat"

  # run tests
  - npm test

# Don't actually build.
build: off
